PROGS := search sort binary

all: $(PROGS)

search: search.cpp
	g++ -g search.cpp -o search

sort: sort.cpp
	g++ -g sort.cpp -o sort

binary: binary.cpp 
	g++ -g binary.cpp -o binary

clean: 
	rm -f $(PROGS) *.o *~